---
- name: Add JFrog Helm Repository
  community.general.helm_repository:
    name: jfrog
    repo_url: https://charts.jfrog.io
    state: present

- name: Update Helm Repositories
  command: helm repo update
  changed_when: false

- name: Create Namespaces for Artifactory Instances
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  loop: "{{ artifactory_instances }}"
  loop_control:
    label: "{{ item.namespace }}"

- name: Create Custom Values Files
  loop: "{{ artifactory_instances }}"
  loop_control:
    label: "{{ item.name }}"
  copy:
    dest: "{{ item.name }}-values.yaml"
    content: |
      artifactory:
        ossEnabled: true
        replicaCount: 1
        service:
          type: ClusterIP
          port: 8081
        resources: {}
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
      ingress:
        enabled: false
      nginx:
        enabled: false

- name: Deploy Artifactory Instances with Helm
  loop: "{{ artifactory_instances }}"
  loop_control:
    label: "{{ item.name }}"
  community.general.helm:
    name: "{{ item.name }}"
    chart_ref: jfrog/artifactory
    namespace: "{{ item.namespace }}"
    values_file: "{{ item.name }}-values.yaml"
    create_namespace: false
    wait: true

