---
- name: Deploy multiple NGINX ingress controllers
  hosts: localhost
  roles:
    - role: nginx_ingress
      vars:
        namespace: ingress-nginx-1
        release_name: ingress-nginx-1
        ingress_class_name: nginx-1

    - role: nginx_ingress
      vars:
        namespace: ingress-nginx-2
        release_name: ingress-nginx-2
        ingress_class_name: nginx-2
- name: Deploy artifactory with mTLS configurations 
  hosts: localhost
  connection: local
  gather_facts: false 
  roles:
    - ca_certificate

