---
- name: Define the backend service name and port
  set_fact:
    backend_service_name: "{{ artifactory_instance.name }}-nginx-service"
    backend_service_port: 8443 

- name: Create Ingress resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ artifactory_instance.name }}-ingress"
        namespace: "{{ artifactory_instance.namespace }}"
        annotations:
          kubernetes.io/ingress.class: "{{ artifactory_instance.ingress_class }}"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
          nginx.ingress.kubernetes.io/auth-tls-secret: "{{ ca_namespace }}/{{ ca_secret_name }}"
          nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
      spec:
        tls:
          - hosts:
              - "{{ artifactory_instance.host }}"
            secretName: "{{ artifactory_instance.name }}-tls-secret"
        rules:
          - host: "{{ artifactory_instance.host }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "{{ backend_service_name }}"
                      port:
                        number: "{{ backend_service_port }}"
