---
- name: Add the ingress-nginx Helm repository
  community.kubernetes.helm_repository:
    repo_name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install the ingress-nginx chart
  community.kubernetes.helm:
    name: "{{ release_name }}"
    chart_ref: ingress-nginx/ingress-nginx
    release_name: "{{ release_name }}"
    create_namespace: true
    release_namespace: "{{ namespace }}"
    update_repo_cache: true
    release_values:
      controller:
        ingressClassResource:
          name: "{{ ingress_class_name }}"
        service:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "{{ azure_lb_health_probe_path }}"
          externalTrafficPolicy: "{{ external_traffic_policy }}"
