name: Validate terraform 

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'terraform/**'
      - '!**/*.md'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validation:
    env:
      tf_actions_working_dir: terraform 
    defaults:
      run:
        working-directory: ./terraform
    concurrency:
      group: terraform 
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_CREDS }}
       
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show 
