name: Validate terraform 

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'terraform/**'
      - '!**/*.md'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  prepare:
    concurrency:
      group: storage 
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Azure credentials
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_CREDS }}

      - name: Setup Ansible
        run:
          ansible-galaxy collection install azure.azcollection --force

      - name: Install dependecies 
        run: 
          ls -lgia /opt/pipx/venvs && pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

      - name: Setup Azure Storage for Terraform Backend
        run:
          ansible-playbook pull-request-playbook.yml
        env:
          RESOURCE_GROUP: ${{ secrets.AZ_RESOURCE_GROUP }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.AZ_STORAGE_ACCOUNT_NAME }}
          CONTAINER_NAME: ${{ secrets.AZ_CONTAINER_NAME }}
